CREATE TYPE "public"."imovel_status" AS ENUM('disponivel', 'reservado', 'vendido', 'alugado');--> statement-breakpoint
CREATE TABLE "imoveis" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"titulo" varchar(255) NOT NULL,
	"descricao" text,
	"tipo" varchar(100) NOT NULL,
	"status" "imovel_status" DEFAULT 'disponivel' NOT NULL,
	"preco" numeric(15, 2) NOT NULL,
	"quartos" integer,
	"banheiros" integer,
	"vagas" integer,
	"area_m2" numeric(10, 2),
	"endereco" text,
	"bairro" varchar(100),
	"cidade" varchar(100) NOT NULL,
	"estado" varchar(2),
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"fotos" text,
	"destaque" boolean DEFAULT false NOT NULL,
	"publicado_site" boolean DEFAULT true NOT NULL,
	"publicado_zap" boolean DEFAULT false NOT NULL,
	"publicado_olx" boolean DEFAULT false NOT NULL,
	"publicado_viva" boolean DEFAULT false NOT NULL,
	"publicado_chaves_na_mao" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "imoveis_slug_unique" UNIQUE("slug")
);
