CREATE TYPE "public"."avaliacao_status" AS ENUM('solicitada', 'vistoria', 'elaboracao', 'revisao', 'entregue', 'cancelada');--> statement-breakpoint
CREATE TABLE "avaliacoes" (
	"id" serial PRIMARY KEY NOT NULL,
	"numero" varchar(30) NOT NULL,
	"tipo" varchar(50) NOT NULL,
	"finalidade" varchar(50) NOT NULL,
	"status" "avaliacao_status" DEFAULT 'solicitada' NOT NULL,
	"cliente_nome" varchar(255) NOT NULL,
	"cliente_cpf" varchar(20),
	"cliente_tel" varchar(20) NOT NULL,
	"cliente_email" varchar(320),
	"endereco" text NOT NULL,
	"bairro" varchar(100) NOT NULL,
	"cidade" varchar(100) NOT NULL,
	"estado" varchar(2) NOT NULL,
	"area_construida" numeric(10, 2),
	"area_terreno" numeric(10, 2),
	"quartos" integer,
	"banheiros" integer,
	"vagas" integer,
	"caracteristicas" text DEFAULT '' NOT NULL,
	"metodologia" varchar(50) DEFAULT 'comparativo' NOT NULL,
	"valor_estimado" numeric(15, 2),
	"avaliador" varchar(255) NOT NULL,
	"data_vistoria" timestamp,
	"prazo_entrega" timestamp,
	"data_entrega" timestamp,
	"observacoes" text DEFAULT '' NOT NULL,
	"laudo" text,
	"documentos" text DEFAULT '[]' NOT NULL,
	"sugestao_json" text,
	"valor_servico" numeric(15, 2),
	"lead_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "avaliacoes_numero_unique" UNIQUE("numero")
);
--> statement-breakpoint
ALTER TABLE "avaliacoes" ADD CONSTRAINT "avaliacoes_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE set null ON UPDATE no action;