CREATE TABLE "incorporation_studies" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"city" varchar(120) NOT NULL,
	"state" varchar(2) DEFAULT 'MA' NOT NULL,
	"address" text,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"responsible" varchar(120),
	"status" varchar(40) DEFAULT 'draft' NOT NULL,
	"property_ref" varchar(180),
	"kml_url" text,
	"geojson" text,
	"area_m2" numeric(15, 2) DEFAULT '0' NOT NULL,
	"perimeter_m" numeric(15, 2) DEFAULT '0' NOT NULL,
	"app_area_m2" numeric(15, 2),
	"app_width_m" numeric(15, 2),
	"app_origin" varchar(40),
	"elevation_json" text,
	"survey_url" text,
	"cut_fill_json" text,
	"urban_parameters_json" text,
	"potential_json" text,
	"urbanistic_opinion" text,
	"city_research_json" text,
	"market_study_json" text,
	"comparable_pricing_json" text,
	"primary_research_json" text,
	"mass_scenarios_json" text,
	"selected_scenario_id" varchar(120),
	"areas_board_json" text,
	"parameterized_budget_json" text,
	"land_negotiation_json" text,
	"business_plan_json" text,
	"designers_json" text,
	"project_approval_json" text,
	"incorporation_registration_json" text,
	"preliminary_budget_json" text,
	"launch_plan_json" text,
	"launch_suppliers_json" text,
	"marketing_material_json" text,
	"real_estate_launch_json" text,
	"executive_projects_json" text,
	"work_budget_json" text,
	"physical_financial_schedule_json" text,
	"customer_service_json" text,
	"product_mix_json" text,
	"feasibility_json" text,
	"schedule_json" text,
	"ai_opinion" text,
	"lotting_json" text,
	"reports_json" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "regularizacao_documents" (
	"id" serial PRIMARY KEY NOT NULL,
	"regularizacao_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"status" varchar(40) DEFAULT 'pending' NOT NULL,
	"observation" text DEFAULT '' NOT NULL,
	"file_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "regularizacoes" (
	"id" serial PRIMARY KEY NOT NULL,
	"client_name" varchar(255) NOT NULL,
	"client_phone" varchar(30),
	"type" varchar(120) NOT NULL,
	"status" varchar(40) DEFAULT 'analysis' NOT NULL,
	"address" text NOT NULL,
	"registration" varchar(120),
	"registry_office" varchar(255),
	"responsible" varchar(120) NOT NULL,
	"lead_id" integer,
	"service_value" numeric(15, 2) DEFAULT '0' NOT NULL,
	"paid_value" numeric(15, 2) DEFAULT '0' NOT NULL,
	"expected_end_at" timestamp,
	"description" text DEFAULT '' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
